curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_nzmh.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_speed_redpocke.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_live_redrain.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_daily_lottery.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_carnivalcity.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_zoo.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_zooCollect.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_xtg.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_xtg_help.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_gold_creator.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_mohe.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_star_shop.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_mcxhd.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_big_winner.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_bean_sign.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_blueCoin.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_club_lottery.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_joy.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_joy_reward.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_joy_feedPets.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_moneyTree.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_plantBean.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_redPacket.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_shop.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_superMarket.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_unsubscribe.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_bean_change.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_lotteryMachine.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_rankingList.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_necklace.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_small_home.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_syj.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_kd.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_car.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_bean_home.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_jdzz.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_crazy_joy.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_car_exchange.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_get_share_code.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_bookshop.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_cash.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_sgmh.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_ms.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_beauty.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_speed_sign.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_cfd.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_live.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_health.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_health_collect.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_market_lottery.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_jin_tie.js
curl -O https://raw.githubusercontent.com/BrendanLiu/jd_diy/fix/scripts/jd_jump.js
